spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:9090
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db-edit-profile
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
eureka:
  client:
    serviceUrl:
      #      defaultZone: http://service-registry:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
