spring:
  kafka:
    bootstrap-servers:
      - 167.172.78.79:9092
      - 167.172.78.79:9093
      - 167.172.78.79:9094
    consumer:
      group-id: bookmark-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual                  # Number of records between offset commits
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:9090
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db-edit-profile
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
eureka:
  client:
    serviceUrl:
      #      defaultZone: http://service-registry:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
