spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db-edit-profile
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG